[project]
authors = ["Brad Paul <c186282@gamil.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "billinn"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
astropy = "*"
numpy = "*"
jupyterlab = "*"
